import express from'express';import{createServer}from'node:http';import{Server,Room,Client,ServerError}from'@colyseus/core';import{WebSocketTransport}from'@colyseus/ws-transport';import{initDb,leaderboard,saveResults}from'./db.js';import{TRACKS,emptyControls,stepCar,crossed,type Car,type Controls}from'@heartline/shared';
type Player={car:Car;input:Controls;lastMsg:number};type Phase='lobby'|'countdown'|'racing'|'finished';
class RaceRoom extends Room{maxClients=10;spectators=new Set<string>();players=new Map<string,Player>();phase:Phase='lobby';host='';track=TRACKS[0];startedAt=0;countdownAt=0;recorded=false;
 onCreate(){this.setSimulationInterval(dt=>this.tick(Math.min(dt/1000,.05)),1000/30);this.onMessage('profile',(cl,d)=>{const p=this.players.get(cl.sessionId);if(!p||!this.rate(p)||typeof d?.name!=='string'||!/[\w .'-]{1,18}$/.test(d.name)||!/^#[0-9a-f]{6}$/i.test(d.color))return;p.car.name=d.name;p.car.color=d.color;p.car.model=['sport','drift','muscle'].includes(d.model)?d.model:'sport';p.car.ready=!!d.ready;this.sync()});this.onMessage('track',(cl,id)=>{if(cl.sessionId!==this.host||this.phase!=='lobby')return;const next=TRACKS.find(t=>t.id===id);if(!next)return;this.track=next;this.reset();this.sync()});this.onMessage('input',(cl,d)=>{const p=this.players.get(cl.sessionId);if(!p||!this.rate(p)||!Number.isInteger(d?.seq))return;p.input={seq:d.seq,throttle:Number(d.throttle)||0,steer:Number(d.steer)||0,brake:!!d.brake,boost:!!d.boost}});this.onMessage('start',cl=>{if(cl.sessionId!==this.host||this.players.size!==2||![...this.players.values()].every(p=>p.car.ready))return;this.phase='countdown';this.recorded=false;this.countdownAt=Date.now()+3500;this.sync()});this.onMessage('rematch',cl=>{const p=this.players.get(cl.sessionId);if(!p||this.phase!=='finished')return;p.car.ready=true;if([...this.players.values()].every(x=>x.car.ready)){this.reset();this.phase='countdown';this.recorded=false;this.countdownAt=Date.now()+3500}this.sync()})}
 onJoin(cl:Client,opts:any){if(opts?.spectate){this.spectators.add(cl.sessionId);this.sync();return}if(this.players.size>=2)throw new ServerError(4001,'Race already has two racers');const name=typeof opts?.name==='string'&&/^[\w .'-]{1,18}$/.test(opts.name)?opts.name:'Racer',color=/^#[0-9a-f]{6}$/i.test(opts?.color)?opts.color:'#ff5b75',model=['sport','drift','muscle'].includes(opts?.model)?opts.model:'sport',i=this.players.size;this.players.set(cl.sessionId,{car:{id:cl.sessionId,name,color,model,x:this.track.spawn[0]+i*35,y:this.track.spawn[1],angle:this.track.spawn[2],vx:0,vy:0,lap:1,checkpoint:1,finishedAt:null,boost:0,ready:false,connected:true},input:emptyControls(),lastMsg:0});if(!this.host)this.host=cl.sessionId;this.sync()}
 async onLeave(cl:Client,code?:number){if(this.spectators.delete(cl.sessionId))return;const p=this.players.get(cl.sessionId);if(!p)return;p.car.connected=false;p.car.disconnectedAt=Date.now();this.sync();try{if(code===4000)return this.drop(cl.sessionId);await this.allowReconnection(cl,15);p.car.connected=true;p.car.disconnectedAt=undefined;this.sync()}catch{this.drop(cl.sessionId)}}
 drop(id:string){this.players.delete(id);if(this.host===id)this.host=[...this.players.keys()][0]||'';if(this.phase==='racing')this.phase='finished';this.sync()}rate(p:Player){const now=Date.now();if(now-p.lastMsg<8)return false;p.lastMsg=now;return true}
 reset(){let i=0;for(const p of this.players.values()){Object.assign(p.car,{x:this.track.spawn[0]+i++*35,y:this.track.spawn[1],angle:this.track.spawn[2],vx:0,vy:0,lap:1,checkpoint:1,finishedAt:null,ready:false});p.input=emptyControls()}}
 tick(dt:number){const now=Date.now();if(this.phase==='countdown'&&now>=this.countdownAt){this.phase='racing';this.startedAt=now}if(this.phase==='racing'){for(const p of this.players.values()){if(!p.car.connected)continue;const old={...p.car};stepCar(p.car,p.input,dt,this.track);crossed(old,p.car,this.track);if(p.car.lap>3&&!p.car.finishedAt)p.car.finishedAt=now-this.startedAt}const cars=[...this.players.values()].map(p=>p.car);if(cars.length===2){const[a,b]=cars,dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d<30){const nx=d?dx/d:1,ny=d?dy/d:0,push=(30-d)/2;a.x-=nx*push;a.y-=ny*push;b.x+=nx*push;b.y+=ny*push}}if(cars.some(c=>c.finishedAt)){this.phase='finished';if(!this.recorded){this.recorded=true;saveResults(this.track.id,cars).catch(console.error)}this.sync();return}}if(this.phase==='countdown'||this.phase==='racing')this.broadcast('state',this.snapshot())}
 snapshot(){return{phase:this.phase,host:this.host,track:this.track,countdownAt:this.countdownAt,serverNow:Date.now(),players:[...this.players.values()].map(p=>p.car),spectators:this.spectators.size}}sync(){this.broadcast('state',this.snapshot())}}
await initDb();const app=express();app.use((_,res,next)=>{res.setHeader('Access-Control-Allow-Origin',process.env.WEB_ORIGIN||'https://hsc-logic.github.io');next()});app.get('/health',(_,res)=>res.json({ok:true}));app.get('/leaderboard',async(_,res)=>{try{res.json(await leaderboard())}catch(error){console.error(error);res.status(503).json({error:'Leaderboard unavailable'})}});const http=createServer(app),game=new Server({transport:new WebSocketTransport({server:http})});game.define('race',RaceRoom).filterBy(['code']);const port=Number(process.env.PORT||2567);await game.listen(port);console.log(`Heartline server :${port}`);
