export type Controls={seq:number;throttle:number;steer:number;brake:boolean;boost:boolean}
export type Car={id:string;name:string;color:string;x:number;y:number;angle:number;vx:number;vy:number;lap:number;checkpoint:number;finishedAt:number|null;boost:number;ready:boolean;connected:boolean;model?:'sport'|'drift'|'muscle'}
export type Track={id:string;name:string;theme:string;width:number;height:number;spawn:[number,number,number];walls:{x:number;y:number;w:number;h:number}[];checkpoints:{x:number;y:number;w:number;h:number;forward:'x'|'y';sign:1|-1}[];boostPads:{x:number;y:number;r:number}[];hazards:{x:number;y:number;r:number}[]}
const border=[{x:0,y:0,w:1200,h:34},{x:0,y:686,w:1200,h:34},{x:0,y:0,w:34,h:720},{x:1166,y:0,w:34,h:720}];
const gates=[{x:75,y:505,w:270,h:18,forward:'y' as const,sign:-1 as const},{x:75,y:80,w:270,h:30,forward:'y' as const,sign:-1 as const},{x:930,y:70,w:220,h:30,forward:'y' as const,sign:1 as const},{x:930,y:590,w:220,h:30,forward:'y' as const,sign:1 as const}];
export const TRACKS:Track[]=[
 {id:'moonlight',name:'Moonlight Loop',theme:'#18363a',width:1200,height:720,spawn:[210,580,-Math.PI/2],walls:[...border,{x:310,y:150,w:580,h:390}],checkpoints:gates,boostPads:[{x:1040,y:350,r:32}],hazards:[{x:600,y:110,r:25}]},
 {id:'coastal',name:'Coastal Rush',theme:'#155c68',width:1200,height:720,spawn:[210,580,-Math.PI/2],walls:[...border,{x:350,y:125,w:500,h:420}],checkpoints:gates,boostPads:[{x:600,y:105,r:32},{x:1030,y:610,r:32}],hazards:[{x:1030,y:300,r:28}]},
 {id:'neon',name:'Neon Circuit',theme:'#3b2454',width:1200,height:720,spawn:[210,580,-Math.PI/2],walls:[...border,{x:285,y:175,w:630,h:340}],checkpoints:gates,boostPads:[{x:180,y:120,r:30},{x:1020,y:600,r:30}],hazards:[{x:600,y:595,r:28},{x:1040,y:340,r:24}]}
];
export const emptyControls=():Controls=>({seq:0,throttle:0,steer:0,brake:false,boost:false});
export function stepCar(c:Car,input:Controls,dt:number,track=TRACKS[0]){if(c.finishedAt)return;const spec=c.model==='muscle'?[290,250,1.8]:c.model==='drift'?[245,305,2.8]:[270,285,2.25],throttle=Math.max(-1,Math.min(1,input.throttle)),steer=Math.max(-1,Math.min(1,input.steer)),speed=Math.hypot(c.vx,c.vy);c.angle+=steer*Math.min(spec[2],1.2+speed/180)*dt*(throttle<0?-0.65:1);let power=spec[0]*throttle;if(input.boost&&c.boost<=0){power+=300;c.boost=4}c.boost=Math.max(0,c.boost-dt);c.vx+=Math.cos(c.angle)*power*dt;c.vy+=Math.sin(c.angle)*power*dt;const drag=Math.pow(input.brake?.90:.985,dt*60);c.vx*=drag;c.vy*=drag;const max=input.boost?410:spec[1],ratio=Math.min(1,max/(Math.hypot(c.vx,c.vy)||1));c.vx*=ratio;c.vy*=ratio;c.x+=c.vx*dt;c.y+=c.vy*dt;for(const pad of track.boostPads)if(Math.hypot(c.x-pad.x,c.y-pad.y)<pad.r){c.vx*=1.018;c.vy*=1.018;c.boost=0}for(const hazard of track.hazards)if(Math.hypot(c.x-hazard.x,c.y-hazard.y)<hazard.r){c.vx*=.94;c.vy*=.94}for(const w of track.walls){const nx=Math.max(w.x,Math.min(c.x,w.x+w.w)),ny=Math.max(w.y,Math.min(c.y,w.y+w.h));const dx=c.x-nx,dy=c.y-ny,d=Math.hypot(dx,dy);if(d<15){const ux=d?dx/d:1,uy=d?dy/d:0;c.x=nx+ux*15;c.y=ny+uy*15;const dot=c.vx*ux+c.vy*uy;if(dot<0){c.vx-=1.7*dot*ux;c.vy-=1.7*dot*uy}}}}
export function crossed(prev:Car,c:Car,track=TRACKS[0]){const cp=track.checkpoints[c.checkpoint];if(!cp)return false;const horizontal=cp.w>=cp.h;const line=horizontal?cp.y+cp.h/2:cp.x+cp.w/2;const before=horizontal?prev.y:prev.x,after=horizontal?c.y:c.x,crossedLine=cp.sign>0?before<line&&after>=line:before>line&&after<=line;if(!crossedLine)return false;const delta=after-before;if(Math.sign(delta)!==cp.sign)return false;const ratio=(line-before)/(delta||1),other=(horizontal?prev.x:prev.y)+((horizontal?c.x:c.y)-(horizontal?prev.x:prev.y))*ratio;const min=horizontal?cp.x:cp.y,max=min+(horizontal?cp.w:cp.h);if(other<min-15||other>max+15)return false;const previousCheckpoint=c.checkpoint;c.checkpoint=(c.checkpoint+1)%track.checkpoints.length;if(previousCheckpoint===0)c.lap++;return true}
